# Generated by Django 4.2 on 2023-06-11 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_forumsection_forumsubsection_delete_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumsubsection',
            options={'verbose_name': 'Тема форума', 'verbose_name_plural': 'Темы форума'},
        ),
        migrations.CreateModel(
            name='ForumCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.TextField(verbose_name='Текст')),
                ('date_text', models.DateField(auto_now=True, verbose_name='Дата сообщения')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumsubsection', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждения',
                'ordering': ['-date_text'],
            },
        ),
    ]
