# Generated by Django 4.2 on 2023-06-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumsubsection_options_forumcommunication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsection',
            name='section',
            field=models.CharField(max_length=300, verbose_name='Раздел'),
        ),
    ]
