# Generated by Django 4.2 on 2023-05-14 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('group_photo', models.ImageField(default='dflt_crs_hdrs.jpg', upload_to='groups_headers/%Y/%m/%d', verbose_name='Изображение группы')),
                ('about_the_group', models.TextField(verbose_name='О группе')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='Автор группы')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='PostsInStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='posts_images/%Y/%m/%d', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл')),
                ('post_text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменеия')),
                ('post_type', models.CharField(choices=[('1', 'Лекция'), ('2', 'Практика')], max_length=200, verbose_name='Тип поста')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_groups.studygroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Пост курса',
                'verbose_name_plural': 'Посты курса',
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='CompletedTaskInStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='compl_tasks/%Y/%m/%d', verbose_name='Файл')),
                ('time_load', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_groups.studygroup', verbose_name='Учебная группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
                'ordering': ['-time_load'],
            },
        ),
    ]
