# Generated by Django 4.2 on 2023-05-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsinstudygroup',
            options={'ordering': ['-time_created'], 'verbose_name': 'Материал группы', 'verbose_name_plural': 'Метериалы группы'},
        ),
    ]
