# Generated by Django 4.2 on 2023-05-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_alter_postsinstudygroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtaskinstudygroup',
            name='study_group',
        ),
        migrations.AddField(
            model_name='completedtaskinstudygroup',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study_groups.postsinstudygroup', verbose_name='Учебная группа'),
            preserve_default=False,
        ),
    ]
