# Generated by Django 4.2 on 2023-05-17 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_groups', '0003_remove_completedtaskinstudygroup_study_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценивания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_groups.completedtaskinstudygroup', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
