# Generated by Django 4.2 on 2023-05-17 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0004_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
