# Generated by Django 4.2 on 2023-05-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0005_valuation_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='compl_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='study_groups.completedtaskinstudygroup', verbose_name='Выполненное задание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valuation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_groups.postsinstudygroup', verbose_name='Задание'),
        ),
    ]
