# Generated by Django 4.2 on 2023-05-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0006_valuation_compl_task_alter_valuation_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuation',
            old_name='task',
            new_name='post_task',
        ),
    ]
