# Generated by Django 4.2 on 2023-05-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0007_rename_task_valuation_post_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtaskinstudygroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_groups.postsinstudygroup', verbose_name='Задание'),
        ),
    ]
