# Generated by Django 4.2 on 2023-05-18 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0009_completedtaskinstudygroup_valuation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtaskinstudygroup',
            name='valuation',
        ),
        migrations.AddField(
            model_name='completedtaskinstudygroup',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
