# Generated by Django 4.2 on 2023-05-21 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0010_remove_completedtaskinstudygroup_valuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtaskinstudygroup',
            name='grade',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Оценка'),
        ),
    ]
