# Generated by Django 4.2 on 2023-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0013_alter_completedtaskinstudygroup_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='group_code',
            field=models.CharField(default='2YdCG61', max_length=10, verbose_name='Код курса'),
        ),
    ]
