# Generated by Django 4.2 on 2023-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0014_studygroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_code',
            field=models.CharField(default='K79BNtt', max_length=10, verbose_name='Код группы'),
        ),
    ]
