# Generated by Django 4.2 on 2023-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts_images/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_text',
            field=models.TextField(blank=True, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_photo',
            field=models.ImageField(upload_to='courses_headers/%Y/%m/%d', verbose_name='Изображение курса'),
        ),
    ]
