# Generated by Django 4.2 on 2023-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_posts_photo_posts_post_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_photo',
            field=models.ImageField(blank=True, upload_to='courses_headers/%Y/%m/%d', verbose_name='Изображение курса'),
        ),
    ]
