# Generated by Django 4.2 on 2023-04-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_posts_file_alter_courses_course_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
