# Generated by Django 4.2 on 2023-04-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_completedtaskmodel_options_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_photo',
            field=models.ImageField(default='dflt_crs_hdrs.jpg', upload_to='courses_headers/%Y/%m/%d', verbose_name='Изображение курса'),
        ),
    ]
