# Generated by Django 4.2 on 2023-04-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courses_course_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-time_created'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='courses',
            name='about_the_course',
            field=models.TextField(default=1, verbose_name='О курсе'),
            preserve_default=False,
        ),
    ]
