# Generated by Django 4.2 on 2023-04-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_courses'),
        ('courses', '0014_alter_courses_author_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
