# Generated by Django 4.2 on 2023-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('1', 'Лекция'), ('2', 'Практика')], default=1, max_length=200, verbose_name='Тип поста'),
            preserve_default=False,
        ),
    ]
