# Generated by Django 4.2 on 2023-05-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_created'], 'verbose_name': 'Пост курса', 'verbose_name_plural': 'Посты курса'},
        ),
    ]
