# Generated by Django 4.2 on 2023-05-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_courses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='type_course',
            field=models.CharField(choices=[('1', 'Публичный'), ('2', 'Платный')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.category', verbose_name='Категория'),
        ),
    ]
