# Generated by Django 4.2 on 2023-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_courses_price_courses_type_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='type_course',
            field=models.CharField(choices=[('1', 'Публичный'), ('2', 'Платный')], default='1', max_length=200, verbose_name='Тип курса'),
        ),
    ]
