# Generated by Django 4.2 on 2023-05-25 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0022_alter_courses_type_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название теста')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('true_answer', models.CharField(max_length=300, verbose_name='Правильный ответ')),
                ('user_answer', models.CharField(max_length=300, verbose_name='Ответ пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест с вписыванием ответа',
                'verbose_name_plural': 'Тесты с вписыванием ответа',
            },
        ),
    ]
