# Generated by Django 4.2 on 2023-05-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
