# Generated by Django 4.2 on 2023-05-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-04-04 10:54:06.032441', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
