# Generated by Django 4.2 on 2023-05-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_quiz_time_created_quiz_time_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-time_created'], 'verbose_name': 'Тест с вписыванием ответа', 'verbose_name_plural': 'Тесты с вписыванием ответа'},
        ),
    ]
