# Generated by Django 4.2 on 2023-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_question_testing_reply_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time_updated',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
