# Generated by Django 4.2 on 2023-06-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_questionmodel_alter_answermodel_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
