# Generated by Django 4.2 on 2023-06-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_questionmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='true_answer',
            field=models.CharField(default=1, max_length=500, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
