# Generated by Django 4.2 on 2023-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_questionmodel_true_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс'),
        ),
    ]
