# Generated by Django 4.2 on 2023-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_courses_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Прогресс'),
        ),
    ]
