# Generated by Django 4.2 on 2023-06-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_remove_courses_progress_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.progress', verbose_name='Прогресс'),
            preserve_default=False,
        ),
    ]
