# Generated by Django 4.2 on 2023-06-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_remove_progress_course_courses_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='progress',
        ),
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
