# Generated by Django 4.2 on 2023-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_remove_courses_progress_progress_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
