# Generated by Django 4.2 on 2023-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='avatars/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
