# Generated by Django 4.2 on 2023-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courses_author_enrollment'),
        ('users', '0007_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(through='courses.Enrollment', to='courses.courses', verbose_name='Курсы'),
        ),
    ]
