# Generated by Django 4.2 on 2023-04-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
    ]
