# Generated by Django 4.2 on 2023-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_delete_enrollment'),
        ('users', '0009_remove_customuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='courses.courses', verbose_name='Курсы'),
        ),
    ]
