# Generated by Django 4.2 on 2023-04-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='courses',
            new_name='user_courses',
        ),
    ]
