# Generated by Django 4.2 on 2023-05-09 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_posts_post_type'),
        ('users', '0013_rename_followers_customuser_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_courses',
            field=models.ManyToManyField(blank=True, to='courses.courses', verbose_name='Курсы'),
        ),
    ]
