# Generated by Django 4.2 on 2023-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        ('users', '0014_alter_customuser_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='study_groups.studygroup', verbose_name='Учебные группы'),
        ),
    ]
