# Generated by Django 4.1.6 on 2023-02-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_courses_options_courses_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='image',
            new_name='photo',
        ),
    ]
