# Generated by Django 4.1.6 on 2023-02-25 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_image_courses_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses_header_image/%Y/%m/%d/', verbose_name='Изображение курса'),
        ),
    ]
