# Generated by Django 4.1.6 on 2023-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, default='dflt_crs_hdrs.jpg', upload_to='courses_header_image/%Y/%m/%d', verbose_name='Изображение курса'),
        ),
    ]
