# Generated by Django 4.1.6 on 2023-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_courses_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='type_course',
            field=models.CharField(choices=[('1', 'Публичный'), ('2', 'Доступ по коду'), ('3', 'Платный')], default=1, max_length=200),
        ),
    ]
